package hu.kristof.nagy.hikebookclient.view.help

enum class HelpRequestType {
    MY_MAP, MY_MAP_LIST, MY_MAP_DETAIL,
    ROUTE_CREATE, ROUTE_EDIT,
    BROWSE_LIST, BROWSE_DETAIL,
    GROUP_HIKE, GROUP_HIKE_DETAIL,
    GROUPS, GROUPS_DETAIL_MAP, GROUPS_DETAIL_LIST, GROUPS_DETAIL_MEMBERS,
    HIKE_PLAN_START, HIKE_PLAN_TRANSPORT, HIKE_TRANSPORT, HIKE
}